[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = "2.0"
quote = "1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
walkdir = "2.3.3"
proc-macro2 = "1.0.56"
convert_case = "0.6.0"

[lib]
proc-macro = true
